name: release

on:
  push:
    branches: [ main, develop ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: testing...
        run: |
          echo "Testing of ${{ github.repository }}"

  deploy-development:
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: development
      url: 'develop.example.com'
    permissions:
      contents: read
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: starting...
        run: |
          echo "Deployed to Development"
     
  deploy-staging:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: 'staging.example.com'
    permissions:
      contents: read
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: starting...
        run: |
          echo "Deployed to Staging"

  deploy-production:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'http://www.example.com'
    permissions:
      contents: write
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: starting...
        run: |
          echo "Deployed to Production"
